services:
  redis:
    image: redis:alpine
    container_name: jm_redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Django Web service
  web:
    build: .
    image: pjm314159/jm-web:latest
    container_name: jm_django_web
    volumes:
      - ./JmWebProject/media:/app/JmWebProject/media
      - ./JmWebProject/db:/app/JmWebProject/db
#    ports:
#      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  # Celery Worker service
  celery_worker:
    build: .
    image: pjm314159/jm_celery:latest
    user: "root"
    container_name: jm_celery_worker
    volumes:
      - ./JmWebProject/media:/app/JmWebProject/media
      - ./JmWebProject/db:/app/JmWebProject/db
    command: celery -A JmWebProject worker --loglevel=info --pool=threads
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web
    restart: unless-stopped

  # Celery Beat 定时任务调度器
  celery_beat:
    build: .
    image: pjm314159/jm_celery:latest
    container_name: jm_celery_beat
    volumes:
      - ./JmWebProject/media:/app/JmWebProject/media
      - ./JmWebProject/db:/app/JmWebProject/db
    command: celery -A JmWebProject beat --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: jm_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./JmWebProject/static:/static
      - ./JmWebProject/media:/app/JmWebProject/media
    ports:
      - "8000:80"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  redis_data:
  static_volume: