import os
from datetime import timedelta
from pathlib import Path

from django.db.backends.signals import connection_created

"""
Django settings for JmWebProject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() in ("true", "1", "yes")

# 1. 登录模块配置
SESSION_COOKIE_AGE = int(os.environ.get("SESSION_COOKIE_AGE", "604800"))
AUTH_USER_MODEL = "user.User"

# 2. 媒体文件配置 (用于存储爬取图片)
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = "/media/"
MEDIA_ROOT = os.environ.get("MEDIA_ROOT", os.path.join(BASE_DIR, "media"))

# 3. Redis / 下载模块配置
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")

# 异步爬虫并发控制
JM_DOWNLOAD_IMAGE_CONCURRENCY = int(os.environ.get("JM_DOWNLOAD_IMAGE_CONCURRENCY", "30"))
JM_DOWNLOAD_PHOTO_CONCURRENCY = int(os.environ.get("JM_DOWNLOAD_PHOTO_CONCURRENCY", "3"))
RUST_DOWNLOADER_URL = os.environ.get("RUST_DOWNLOADER_URL", "http://127.0.0.1:3080")
# Rust 下载完成后的回调地址（Docker 内为 http://web:8000）
CRAWL_CALLBACK_URL = os.environ.get("CRAWL_CALLBACK_URL", "http://127.0.0.1:8000")
# Django→Rust HTTP 请求超时与连接池
RUST_REQUEST_TIMEOUT = int(os.environ.get("RUST_REQUEST_TIMEOUT", "15"))
RUST_HTTP_MAX_CONNECTIONS = int(os.environ.get("RUST_HTTP_MAX_CONNECTIONS", "10"))
RUST_HTTP_MAX_KEEPALIVE = int(os.environ.get("RUST_HTTP_MAX_KEEPALIVE", "5"))
# 下载任务状态缓存过期时间（秒）
CRAWL_STATE_TTL = int(os.environ.get("CRAWL_STATE_TTL", str(3600 * 24)))

# jmcomic 客户端配置
JM_OPTION_TIMEOUT = int(os.environ.get("JM_OPTION_TIMEOUT", "30"))
JM_OPTION_RETRY_TIMES = int(os.environ.get("JM_OPTION_RETRY_TIMES", "5"))
JM_OPTION_DOMAINS = [
    d.strip() for d in os.environ.get("JM_OPTION_DOMAINS", "").split(",") if d.strip()
] or None
# 代理地址（jmcomic 与 Rust 下载服务共用，留空/不设置则不使用代理）
PROXY = os.environ.get("PROXY", "").strip() or None

# 阅读器/搜索分页与缓存 TTL
IMAGES_PER_PAGE = int(os.environ.get("IMAGES_PER_PAGE", "300"))
LIST_PAGE_SIZE = int(os.environ.get("LIST_PAGE_SIZE", "30"))
SEARCH_CACHE_TTL = int(os.environ.get("SEARCH_CACHE_TTL", "120"))
DETAIL_CACHE_TTL = int(os.environ.get("DETAIL_CACHE_TTL", "120"))
COMMENT_CACHE_TTL = int(os.environ.get("COMMENT_CACHE_TTL", "60"))
ANON_THROTTLE_RATE = os.environ.get("ANON_THROTTLE_RATE", "30/min")

# 本地媒体扩展名（逗号分隔，含点）
LOCAL_IMAGE_EXTS = [
    e.strip()
    for e in os.environ.get("LOCAL_IMAGE_EXTS", ".jpg,.jpeg,.png,.webp,.gif").split(",")
    if e.strip()
]
LOCAL_VIDEO_EXTS = [
    e.strip()
    for e in os.environ.get("LOCAL_VIDEO_EXTS", ".mp4,.webm,.mov,.mkv").split(",")
    if e.strip()
]

# 5. 缓存配置 (Redis)
CACHE_DEFAULT_TIMEOUT = int(os.environ.get("CACHE_DEFAULT_TIMEOUT", "300"))
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://localhost:6379/0"),
        "TIMEOUT": CACHE_DEFAULT_TIMEOUT,
        "KEY_PREFIX": "jmw",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Session 使用缓存存储
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
SESSION_SAVE_EVERY_REQUEST = False

# 4. 注册密钥 (硬编码，您可以考虑存放在环境变量中)
REGISTRATION_SECRET_KEY = os.getenv("REGISTRATION_SECRET_KEY")
if not REGISTRATION_SECRET_KEY:
    raise RuntimeError("REGISTRATION_SECRET_KEY environment variable is required")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "django-insecure-jnjgzo5%d43(iyjp3zsbc)^($zq@nh)kx0vfbl&6fm9_z*u+sf"
)


ALLOWED_HOSTS = [os.getenv("ALLOWED_HOST"), "127.0.0.1", "localhost", "web"]
# security
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 第三方：REST API + JWT 认证 + CORS
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    # 业务应用
    "user",
    "comic",
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # 须置于 CommonMiddleware 之前
    "django.middleware.gzip.GZipMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.http.ConditionalGetMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS", "http://127.0.0.1,http://127.0.0.1:8000"
).split(",")
CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS", "http://127.0.0.1,http://127.0.0.1:8000"
).split(",")
CORS_ALLOW_CREDENTIALS = True

# ------------------------------------------------------------------
# Django REST Framework：默认 JWT 鉴权 + 统一分页（30/页，对齐旧版列表）
# ------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": LIST_PAGE_SIZE,
    "DEFAULT_THROTTLE_CLASSES": ("rest_framework.throttling.AnonRateThrottle",),
    "DEFAULT_THROTTLE_RATES": {
        "anon": ANON_THROTTLE_RATE,
    },
}

# ------------------------------------------------------------------
# SimpleJWT：access 7d + refresh 7d，旋转 + 拉黑
# ------------------------------------------------------------------
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
ROOT_URLCONF = "JmWebProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
]

WSGI_APPLICATION = "JmWebProject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("DB_NAME", str(BASE_DIR / "db" / "db.sqlite3")),
        "OPTIONS": {
            "timeout": int(os.environ.get("DB_TIMEOUT", "5")),
        },
        "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
    }
}


# SQLite PRAGMA 优化：通过信号在连接创建时执行
def _set_sqlite_pragma(sender, connection, **kwargs):
    if connection.vendor == "sqlite":
        cursor = connection.cursor()
        cursor.execute("PRAGMA journal_mode=WAL;")
        cursor.execute("PRAGMA synchronous=NORMAL;")
        cursor.execute("PRAGMA cache_size=-20000;")
        cursor.execute("PRAGMA busy_timeout=5000;")
        cursor.execute("PRAGMA temp_store=MEMORY;")


connection_created.connect(_set_sqlite_pragma)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# ------------------------------------------------------------------
# 日志配置：控制台 + 按天滚动文件
# ------------------------------------------------------------------
LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")
LOG_DIR = Path(os.getenv("DJANGO_LOG_DIR", BASE_DIR / "logs"))
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {process:d} {thread:d} | {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{asctime}] {levelname} {name} | {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "JmWebProject.log_utils.CompressedTimedRotatingFileHandler",
            "filename": LOG_DIR / "jmweb.log",
            "when": "midnight",
            "backupCount": 30,
            "encoding": "utf-8",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.request": {  # 4xx/5xx 请求日志
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "comic.services.crawl": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "jmcomic": {  # 第三方库降噪
            "level": "WARNING",
        },
    },
}
