# Generated by Django 6.0 on 2025-12-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jm_id', models.CharField(max_length=50, unique=True, verbose_name='JM ID')),
                ('name', models.CharField(default='未知', max_length=255, verbose_name='本子名称')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签列表')),
                ('actors', models.JSONField(blank=True, default=list, verbose_name='角色列表')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('total_episodes', models.IntegerField(default=0, verbose_name='总章节数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_path', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jm_id', models.CharField(max_length=50, unique=True, verbose_name='章节 ID')),
                ('name', models.CharField(max_length=255, verbose_name='章节名称')),
                ('sort_index', models.IntegerField(default=0, verbose_name='章节序号')),
                ('is_downloaded', models.BooleanField(default=False)),
                ('save_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='保存路径')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='comic.album')),
            ],
            options={
                'ordering': ['sort_index'],
            },
        ),
    ]
