# Generated by Django 6.0.6 on 2026-06-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_downloaded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['album', 'is_downloaded'], name='comic_photo_album_i_516442_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['album', 'sort_index'], name='comic_photo_album_i_f00ab9_idx'),
        ),
    ]
