# Generated by Django 6.0.7 on 2026-07-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_alter_photo_is_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
