# Generated by Django 6.0.7 on 2026-08-15 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_add_album_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedJmAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='JM 用户名')),
                ('password', models.TextField(verbose_name='加签后的 JM 密码')),
                ('account_info', models.JSONField(blank=True, default=dict, verbose_name='账号信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jm_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '关联 JM 账号',
            },
        ),
    ]
